name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1

      - name: Install Express
        run: |
          cd progressBarMaker
          bun install express
        
      - name: Run code
        run: |
          cd progressBarMaker
          bun server.ts
